## 결측값 개념과 탐색

### 결측값이란?
- 데이터셋에서 특정값이 누락된 상태
- 결측값은 분석, 시각화, 모델링 등에 오류 또는 왜곡을 일으킬 수 있음

In [1]:
import pandas as pd

data = {
    '이름': ['철수', '영희', '민수', '선호'],
    '나이': [25, None, 30, 28],
    '성별': ['남', '여', '남', None]
}

df = pd.DataFrame(data)
df

   이름    나이    성별
0  철수  25.0     남
1  영희   NaN     여
2  민수  30.0     남
3  선호  28.0  None

#### 결측값 탐색
1. `isnull()`
- 각 원소가 결측값인지 아닌지 Boolean(True/False)로 반환

In [2]:
df.isnull()

      이름     나이     성별
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False   True

2. `isnull().sum()`
- 열 단위로 결측값 개수 집계
- (참고) True: 1 , False: 0

In [3]:
df.isnull().sum()

이름    0
나이    1
성별    1
dtype: int64

### 결측값 채우기
#### (1) `fiilna()` 함수를 활용하여, 결측값을 원하는 값으로 채우기

#### 1. 특정 값으로 채우기

In [4]:
df['나이'].fillna(0)

0    25.0
1     0.0
2    30.0
3    28.0
Name: 나이, dtype: float64

#### 2. 열의 평균값으로 채우기

In [7]:
df['나이'].fillna(df['나이'].mean())

0    25.000000
1    27.666667
2    30.000000
3    28.000000
Name: 나이, dtype: float64

#### 3. 열의 최빈값으로 채우기

In [8]:
df['성별'].fillna(df['성별'].mode()[0])

0    남
1    여
2    남
3    남
Name: 성별, dtype: object

#### (참고) mode() 함수에 대하여
- mode에는 '유행' 이라는 의미가 있음.
- 데이터 중에서 가장 유행하는 값을 가져와라 라는 뜻

왜 mode() 함수를 쓰고 [0]을 가져올까?
- mode() 함수를 쓰면 Series(`{index: value}`)의 형태로 뱉어냄 
- (참고) 여러 개의 최빈 값이 존재할 수 있기 때문에 Series 형태로 반환 함.
- 그래서 return 된 최빈값 중 가장 첫번째 값으로 채우자! 라는 의미로 [0]을 붙여줌

In [9]:
df['성별'].mode()

0    남
Name: 성별, dtype: object

In [10]:
df['성별'].mode()[0]

'남'

#### (2) `bfill`, `ffill` 함수로 이전/다음 값으로 채우기

#### 1. 이전 값으로 채우기 : `ffill()`
(의미) Forward Fill

In [11]:
df

   이름    나이    성별
0  철수  25.0     남
1  영희   NaN     여
2  민수  30.0     남
3  선호  28.0  None

In [12]:
df.ffill()

   이름    나이 성별
0  철수  25.0  남
1  영희  25.0  여
2  민수  30.0  남
3  선호  28.0  남

#### 2. 다음 값으로 채우기: `bfill()`
(의미) Backward Fill

In [14]:
df

   이름    나이    성별
0  철수  25.0     남
1  영희   NaN     여
2  민수  30.0     남
3  선호  28.0  None

In [15]:
df.bfill()

   이름    나이    성별
0  철수  25.0     남
1  영희  30.0     여
2  민수  30.0     남
3  선호  28.0  None

### 결측값 제거

#### `dropna()` 함수로 결측값 제거
(참고) na의 의미: Not Available(NA) 이용할 수 없는
#### 1. 결측값 포함된 행 전체 제거

In [17]:
df

   이름    나이    성별
0  철수  25.0     남
1  영희   NaN     여
2  민수  30.0     남
3  선호  28.0  None

In [16]:
df.dropna()

   이름    나이 성별
0  철수  25.0  남
2  민수  30.0  남

#### 2. 특정 열 기준으로 제거

In [19]:
df.dropna(subset=['성별']) #subset: 부분집합

   이름    나이 성별
0  철수  25.0  남
1  영희   NaN  여
2  민수  30.0  남