## 정렬
- 데이터를 오름차순 또는 내림차순으로 정렬하여 원하는 순서대로 나열
- 데이터 분석 전 데이터 흐름 파악, 상위/하위 항목 추출 등에 활용

In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve',
             'Frank', 'Grace', 'Hannah', 'Ian', 'Judy'],
    'Salary': [3200, 3400, 3100, 8000, 3300,
               3600, 9000, 3000, 3400, 9500],
    'Age': [25, 28, 26, 27, 29,
            30, 26, 31, 32, 28]
}
df = pd.DataFrame(data)
df

      Name  Salary  Age
0    Alice    3200   25
1      Bob    3400   28
2  Charlie    3100   26
3    David    8000   27
4      Eve    3300   29
5    Frank    3600   30
6    Grace    9000   26
7   Hannah    3000   31
8      Ian    3400   32
9     Judy    9500   28

### 1. 단일 컬럼 정렬 (sort_values)
- `by`: 정렬 기준이 되는 컬럼 이름
- 기본 정렬 방향은 오름차순(`ascending=Ture`), 내림차순 정렬은 `ascending=False`

In [2]:
df.sort_values(by='Salary')

      Name  Salary  Age
7   Hannah    3000   31
2  Charlie    3100   26
0    Alice    3200   25
4      Eve    3300   29
1      Bob    3400   28
8      Ian    3400   32
5    Frank    3600   30
3    David    8000   27
6    Grace    9000   26
9     Judy    9500   28

In [3]:
df.sort_values(by='Salary', ascending=False)

      Name  Salary  Age
9     Judy    9500   28
6    Grace    9000   26
3    David    8000   27
5    Frank    3600   30
1      Bob    3400   28
8      Ian    3400   32
4      Eve    3300   29
0    Alice    3200   25
2  Charlie    3100   26
7   Hannah    3000   31

### 2. 다중 컬럼 기준 정렬(sort_values)

In [4]:
df.sort_values(by=['Salary', 'Age'], ascending=[True, False])

      Name  Salary  Age
7   Hannah    3000   31
2  Charlie    3100   26
0    Alice    3200   25
4      Eve    3300   29
8      Ian    3400   32
1      Bob    3400   28
5    Frank    3600   30
3    David    8000   27
6    Grace    9000   26
9     Judy    9500   28

> ### inplace 옵션
> (1) inplace = False (기본 값)
> - 원본 객체는 변경되지 않으며, 변경된 내용이 반영된 새 객체를 반환
> 
> (2) inplcae = True
> - 원본 객체를 직접 변경하며, 메서드는 None을 반환

In [6]:
df = pd.DataFrame({'A': [3,1,2]})

# inplace = False (기본값)
new_df = df.sort_values(by='A') # 정렬된 새 객체 반환
print(new_df)
print(df)

# inplace = True
df.sort_values(by='A', inplace=True)
print(df)

   A
1  1
2  2
0  3
   A
0  3
1  1
2  2
   A
1  1
2  2
0  3