In [3]:
import pandas as pd

data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT'],
    'Salary': [3000, 3500, 2800, 2900, 4000, 4200]
}

df = pd.DataFrame(data)
df

  Department  Salary
0      Sales    3000
1      Sales    3500
2         HR    2800
3         HR    2900
4         IT    4000
5         IT    4200

## 그룹핑
### 그룹핑의 개념
#### 그룹핑(Groupby)
- 데이터를 특정 기준으로 묶어 요약 통계를 게산하는 과정
- 그룹별 평균, 합계, 개수 등을 계산하여 집단 간 비교 가능
- `df.groupyb('기준컬럼')['계산컬럼'].집계함수()`

In [5]:
# 부서별 평균 연봉 
# groupby는 분할 -> 처리 -> 병합 순으로 작동
grouped = df.groupby('Department')['Salary'].mean()
grouped

Department
HR       2850.0
IT       4100.0
Sales    3250.0
Name: Salary, dtype: float64

In [6]:
# 여러 기준으로 그룹핑
data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT'],
    'Gender': ['M', 'F', 'M', 'F', 'M', 'F'],
    'Salary': [3000, 3500, 2800, 2900, 4000, 4200]
}

df = pd.DataFrame(data)

# 부서별 + 성별 평균 연봉 
grouped = df.groupby(['Department', 'Gender'])['Salary'].mean()
grouped

Department  Gender
HR          F         2900.0
            M         2800.0
IT          F         4200.0
            M         4000.0
Sales       F         3500.0
            M         3000.0
Name: Salary, dtype: float64

> #### 여러 집계함수 적용하기 `agg()`
> - agg -> Aggreagate(집계하다, 합계하다)의 약자

In [11]:
import pandas as pd

data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT'],
    'Salary': [3000, 3500, 2800, 2900, 4000, 4200],
    'Bonus': [200, 250, 180, 160, 300, 320]
}

df = pd.DataFrame(data)

# 부서별 평균 급여와 총 보너스를 함께 계산
result = df.groupby('Department').agg({'Salary': 'mean', 'Bonus': 'sum'})
result

            Salary  Bonus
Department
HR          2850.0    340
IT          4100.0    620
Sales       3250.0    450

### 그룹핑 다루기
#### 그룹별 결측값 채우기
- `transform('mean')을 사용하면 각 그룹의 평균값이 원래 행(row)에 그대로 반영
- 행(row)수가 유지되므로, 결측값 채우기에 적합

In [17]:
data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT'],
    'Salary': [3000, None, 2800, 2900, 4000, 4200]
}
df = pd.DataFrame(data)

cond = df.groupby('Department')['Salary'].transform('mean')
df['Salary'] = df['Salary'].fillna(cond)
df

  Department  Salary
0      Sales  3000.0
1      Sales  3000.0
2         HR  2800.0
3         HR  2900.0
4         IT  4000.0
5         IT  4200.0

#### 그룹별 최고/최저 찾기
- `idxmax()`: 가장 큰 값을 가진 인덱스(그룹명) 반환
- `idxmin()`: 가장 작은 값을 가진 그룹명 반환

In [18]:
grouped = df.groupby('Department')['Salary'].mean()
grouped

Department
HR       2850.0
IT       4100.0
Sales    3000.0
Name: Salary, dtype: float64

In [19]:
print(grouped.idxmax()) # 평균 급여 가장 높은 부서
print(grouped.idxmin()) # 평균 급여 가장 낮은 부서

IT
HR