In [4]:
import pandas as pd

data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'Sales', 'IT', 'IT'],
    'Gender': ['M', 'F', 'M', 'F', 'M', 'M', 'F'],
    'Salary': [3000, 3200, 2500, 2700, 3100, 4000, 3900]
}

df = pd.DataFrame(data)

## 피벗테이블(Pivot Table) 이란?
- 데이터를 요약(집계)하고 차원 축소하여 가독성 높은 형태로 재구성하는 도구
- 행 인덱스(index), 값(values)을 지정하여 집계 함수(aggfunc)로 요약
> groupby -> 단순 집계에 강함. (시험 관점에서는 피벗테이블을 몰라도 된다)

<br>

`pd.pivot_table(index='컬럼A', columns='컬럼B', values='컬럼C', aggfunc='mean')`
| 매개변수 | 설명 |
| ------ | --- |
| Index | 행 인덱스로 사용할 컬럼 |
| columns | 열 이름으로 사용할 컬럼 | 
| values | 집계 대상 컬럼 | 
| aggfunc | 집계 함수 (기본값: mean)|

### 1. 단순 피벗 테이블

In [5]:
pd.pivot_table(df, index='Department', values='Salary', aggfunc='mean')

            Salary
Department
HR          2600.0
IT          3950.0
Sales       3100.0

### 2. 다중 피벗 테이블

In [6]:
pd.pivot_table(df, index='Department', columns='Gender', values='Salary', aggfunc='mean')

Gender           F       M
Department
HR          2700.0  2500.0
IT          3900.0  4000.0
Sales       3200.0  3050.0

### 3. 여러 집계 함수 사용

In [10]:
pd.pivot_table(df, index='Department', columns='Gender', values='Salary', aggfunc=['mean', 'max', 'min'])

              mean           max         min
Gender           F       M     F     M     F     M
Department
HR          2700.0  2500.0  2700  2500  2700  2500
IT          3900.0  4000.0  3900  4000  3900  4000
Sales       3200.0  3050.0  3200  3100  3200  3000

> ### 스택(Stack)과 언스택(UnStack)
> - stack(): wide -> long 형태
> - unstack(): long -> wide 형태

In [15]:
pivot = pd.pivot_table(df, index='Department', columns='Gender', 
                       values='Salary', aggfunc=['mean', 'max', 'min'])
pivot

              mean           max         min
Gender           F       M     F     M     F     M
Department
HR          2700.0  2500.0  2700  2500  2700  2500
IT          3900.0  4000.0  3900  4000  3900  4000
Sales       3200.0  3050.0  3200  3100  3200  3000

In [14]:
pivot1 = pivot.stack()
pivot1

/var/folders/55/9n2pd7rd13d5d5tzgcjg1gqw0000gn/T/ipykernel_32210/933304255.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  pivot1 = pivot.stack()

                     mean   max   min
Department Gender
HR         F       2700.0  2700  2700
           M       2500.0  2500  2500
IT         F       3900.0  3900  3900
           M       4000.0  4000  4000
Sales      F       3200.0  3200  3200
           M       3050.0  3100  3000

In [17]:
pivot2 = pivot1.unstack()
pivot2

              mean           max         min
Gender           F       M     F     M     F     M
Department
HR          2700.0  2500.0  2700  2500  2700  2500
IT          3900.0  4000.0  3900  4000  3900  4000
Sales       3200.0  3050.0  3200  3100  3200  3000