## 날짜/시간 데이터 개념
- 날짜/시간 데이터(datetime)는 단순한 문자열이 아닌, 연산/비교/추출이 가능한 시간 정보 객체
- datetime 자료형으로 변환해야 다양한 분석 및 가공 가능

In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Date1': ['2024-04-20', '2023-07-11', '2021-11-09', '2023-03-29', '2024-12-12'],
    'Date2' : ['20/04/2024', '11/07/2023', '09/11/2021', '29/03/2023', '12/12/2024'],
    'Date3' : ['24:04:20', '23:07:11', '21:11:09', '23:03:29', '24:12:12']
}
df = pd.DataFrame(data)
df

      Name       Date1       Date2     Date3
0    Alice  2024-04-20  20/04/2024  24:04:20
1      Bob  2023-07-11  11/07/2023  23:07:11
2  Charlie  2021-11-09  09/11/2021  21:11:09
3    David  2023-03-29  29/03/2023  23:03:29
4      Eve  2024-12-12  12/12/2024  24:12:12

In [3]:
df.info() # 일반적인 문자열은 object 데이터 타입

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Date1   5 non-null      object
 2   Date2   5 non-null      object
 3   Date3   5 non-null      object
dtypes: object(4)
memory usage: 288.0+ bytes

### datetime 형식 변환
- `pd.to_datetime()`: 문자열을 날짜형으로 변환

In [8]:
df['Date1'] = pd.to_datetime(df['Date1'])
df['Date2'] = pd.to_datetime(df['Date2'])
df['Date3'] = pd.to_datetime(df['Date3'])

df.info()

/var/folders/55/9n2pd7rd13d5d5tzgcjg1gqw0000gn/T/ipykernel_36782/733817558.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date3'] = pd.to_datetime(df['Date3'])

DateParseError: hour must be in 0..23: 24:04:20, at position 0

### format 지정하기
- format=옵션: 명시적으로 날짜 형식을 지정 

|주요 포맷 | 설명 |
| ------ | --- |
| %Y | 연도 4자리(예: 2025) |
| %y | 연도 2자리(예: 25) |
| %m | 월(예: 01~12) | 
| %d | 일(예: 01~31) |
| %H | 시간(예: 00~23) |
| %M | 분(예: 00~59) |
| %S | 초(예: 00~59) |

In [10]:
# %y - 연도(4자리): %m - 월 : %d - 일
df['Date3'] = pd.to_datetime(df['Date3'], format='%y:%m:%d') 
df

      Name      Date1      Date2      Date3
0    Alice 2024-04-20 2024-04-20 2024-04-20
1      Bob 2023-07-11 2023-07-11 2023-07-11
2  Charlie 2021-11-09 2021-11-09 2021-11-09
3    David 2023-03-29 2023-03-29 2023-03-29
4      Eve 2024-12-12 2024-12-12 2024-12-12

### 날짜 정보 추출
- dt 속성으로 날짜 정보 추출

| 주요 포맷 | 설명 |
| ------- | --- |
| dt.year | 연도 추출 |
| dt.month | 월 추출 |
| dt.day | 일 추출 |
|dt.day_name | 요일 추출 |
| dt.hour | 시간 추출 |
| dt.minute | 분 추출 |
| dt.second | 초 추출 |

In [12]:
print(dir(df['Date1'].dt))

['__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__frozen', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_accessors', '_add_delegate_accessors', '_constructor', '_delegate_method', '_delegate_property_get', '_delegate_property_set', '_dir_additions', '_dir_deletions', '_freeze', '_get_values', '_hidden_attrs', '_parent', '_reset_cache', 'as_unit', 'ceil', 'date', 'day', 'day_name', 'day_of_week', 'day_of_year', 'dayofweek', 'dayofyear', 'days_in_month', 'daysinmonth', 'floor', 'freq', 'hour', 'is_leap_year', 'is_month_end', 'is_month_start', 'is_quarter_end', 'is_quarter_start', 'is_year_end', 'is_year_start', 'isocalendar', 'microsecond', 'minute', 'month', 'month_name', 'nanosecond', 'normalize', 'quarter', 'round', 'second', 'strftime', 'time', 'timetz', 'to_period', 'to_pydatetime', 'tz', 'tz_convert', 'tz_localize', 'unit', 'weekday', 'year']

In [14]:
df['Year'] = df['Date1'].dt.year
df

      Name      Date1      Date2      Date3  Year
0    Alice 2024-04-20 2024-04-20 2024-04-20  2024
1      Bob 2023-07-11 2023-07-11 2023-07-11  2023
2  Charlie 2021-11-09 2021-11-09 2021-11-09  2021
3    David 2023-03-29 2023-03-29 2023-03-29  2023
4      Eve 2024-12-12 2024-12-12 2024-12-12  2024

In [16]:
df['Month'] = df['Date1'].dt.month
df

      Name      Date1      Date2      Date3  Year  Month
0    Alice 2024-04-20 2024-04-20 2024-04-20  2024      4
1      Bob 2023-07-11 2023-07-11 2023-07-11  2023      7
2  Charlie 2021-11-09 2021-11-09 2021-11-09  2021     11
3    David 2023-03-29 2023-03-29 2023-03-29  2023      3
4      Eve 2024-12-12 2024-12-12 2024-12-12  2024     12

In [18]:
df['Weekday'] = df['Date1'].dt.day
df

      Name      Date1      Date2      Date3  Year  Month  Weekday
0    Alice 2024-04-20 2024-04-20 2024-04-20  2024      4       20
1      Bob 2023-07-11 2023-07-11 2023-07-11  2023      7       11
2  Charlie 2021-11-09 2021-11-09 2021-11-09  2021     11        9
3    David 2023-03-29 2023-03-29 2023-03-29  2023      3       29
4      Eve 2024-12-12 2024-12-12 2024-12-12  2024     12       12

### 날짜 연산
- datetime은 날짜 간 차이 계산 가능

In [19]:
today = pd.Timestamp('2026-06-16')
df['Days Since'] = (today - df['Date1']).dt.days
df

      Name      Date1      Date2      Date3  Year  Month  Weekday  Days Since
0    Alice 2024-04-20 2024-04-20 2024-04-20  2024      4       20         787
1      Bob 2023-07-11 2023-07-11 2023-07-11  2023      7       11        1071
2  Charlie 2021-11-09 2021-11-09 2021-11-09  2021     11        9        1680
3    David 2023-03-29 2023-03-29 2023-03-29  2023      3       29        1175
4      Eve 2024-12-12 2024-12-12 2024-12-12  2024     12       12         551

### 시간 데이터 해석 주의사항
> #### 시간 반올림 주의
> - 시간 데이터를 평균 등으로 계산할 때, 소수점 단위는 "분"의 소수점이 아닌 "시간의 일부"임에 주의
> - 예를 들어, 30.45분은 30분 45초가 아니라, 0.45*60 = 27초 이므로 30분 27초를 의미

In [21]:
time_avg_min = 30.45
minutes = int(time_avg_min)
seconds = round((time_avg_min - minutes) * 60)

print(f"{minutes}분 {seconds}초")

30분 27초

> #### 시간 차이 계산 주의
> - datetime 간 차이는 timedelta 객체로 반환되며, 이 객체를 바로 나누면 오류 발생
> - 반드시 `dt.total_seconds()`로 변환한 뒤 60으로 나눠 분 단위로 변환

In [33]:
import pandas as pd

df = pd.DataFrame({
    'Start': ['2024-01-01 08:00:00', '2024-01-01 09:10:00'],
    'End':   ['2024-01-01 08:45:00', '2024-01-01 10:00:00']
})

df['Start'] = pd.to_datetime(df['Start'])
df['End'] = pd.to_datetime(df['End'])

df['Datetime_Minutes'] = (df['End'] - df['Start']).dt.total_seconds() / 60
df

                Start                 End  Datetime_Minutes
0 2024-01-01 08:00:00 2024-01-01 08:45:00              45.0
1 2024-01-01 09:10:00 2024-01-01 10:00:00              50.0