### 브로드 캐스팅
하나의 연산이 한 컬럼의 모든 데이터에 적용됨

In [ ]:
pip install pyupbit

In [9]:
import pyupbit
df = pyupbit.get_ohlcv("KRW-BTC")

In [10]:
df.head()

,open,high,low,close,volume,value
2025-11-26 09:00:00,130779000.0,135485000.0,129600000.0,135366000.0,2216.723860,2.929944e+11
2025-11-27 09:00:00,135366000.0,138400000.0,134608000.0,136941000.0,2460.708463,3.364135e+11
2025-11-28 09:00:00,136989000.0,139868000.0,135691000.0,136334000.0,1928.858633,2.652600e+11
2025-11-29 09:00:00,136334000.0,136770000.0,135300000.0,136073000.0,769.167574,1.045862e+11
2025-11-30 09:00:00,136000000.0,137631000.0,135600000.0,135744000.0,776.744970,1.060895e+11

In [15]:
df['open'] = df['open'] + 100

In [16]:
df.head()

,open,high,low,close,volume,value
2025-11-26 09:00:00,130779100.0,135485000.0,129600000.0,135366000.0,2216.723860,2.929944e+11
2025-11-27 09:00:00,135366100.0,138400000.0,134608000.0,136941000.0,2460.708463,3.364135e+11
2025-11-28 09:00:00,136989100.0,139868000.0,135691000.0,136334000.0,1928.858633,2.652600e+11
2025-11-29 09:00:00,136334100.0,136770000.0,135300000.0,136073000.0,769.167574,1.045862e+11
2025-11-30 09:00:00,136000100.0,137631000.0,135600000.0,135744000.0,776.744970,1.060895e+11

### 데이터 프레임 필터링
- 비교 연산자의 결과는 Boolean 값을 갖고 있는 시리즈 객체
- 예) 종가가 고가 보다 높았던 거래일만 필터링 해보기

In [18]:
df = pyupbit.get_ohlcv("KRW-BTC")

cond = df['close'] > df['open']
cond

2025-11-26 09:00:00     True
2025-11-27 09:00:00     True
2025-11-28 09:00:00    False
2025-11-29 09:00:00    False
2025-11-30 09:00:00    False
                       ...
2026-06-09 09:00:00    False
2026-06-10 09:00:00     True
2026-06-11 09:00:00     True
2026-06-12 09:00:00     True
2026-06-13 09:00:00     True
Length: 200, dtype: bool

In [19]:
df[cond] #각 인덱스에 대해서 True인 로우만 필터링

,open,high,low,close,volume,value
2025-11-26 09:00:00,130779000.0,135485000.0,129600000.0,135366000.0,2216.723860,2.929944e+11
2025-11-27 09:00:00,135366000.0,138400000.0,134608000.0,136941000.0,2460.708463,3.364135e+11
2025-12-02 09:00:00,129169000.0,137330000.0,128650000.0,135626000.0,2981.093620,3.966780e+11
2025-12-03 09:00:00,135683000.0,140212000.0,135200000.0,138881000.0,2892.416537,3.997018e+11
2025-12-07 09:00:00,133601000.0,136800000.0,131333000.0,135195000.0,1255.394656,1.681352e+11
...,...,...,...,...,...,...
2026-06-07 09:00:00,92560000.0,97000000.0,92353000.0,95430000.0,1892.840645,1.787384e+11
2026-06-10 09:00:00,92555000.0,94470000.0,91500000.0,92601000.0,1257.280333,1.163889e+11
2026-06-11 09:00:00,92560000.0,95800000.0,92558000.0,95623000.0,1035.236579,9.792810e+10
2026-06-12 09:00:00,95623000.0,96947000.0,94598000.0,96029000.0,933.995494,8.944748e+10
2026-06-13 09:00:00,96029000.0,96438000.0,95801000.0,96435000.0,268.385733,2.580103e+10

### 컬럼 시프트
데이터 프레임의 연산은 기본적으로 같은 인덱스에 있는 컬럼과 컬럼 사이에 적용됨
- `df['high'] - df['low']`

#### Q. 당일 저가와 전일 저가를 빼려면 어떻게 해야 할까? (인덱스가 다른 연산은 어떻게 해야 할까?)
- `df['컬럼명'].shift(1)
    - 특정 컬럼의 데이터를 아래로 하나씩 이동

In [20]:
df.head()

,open,high,low,close,volume,value
2025-11-26 09:00:00,130779000.0,135485000.0,129600000.0,135366000.0,2216.723860,2.929944e+11
2025-11-27 09:00:00,135366000.0,138400000.0,134608000.0,136941000.0,2460.708463,3.364135e+11
2025-11-28 09:00:00,136989000.0,139868000.0,135691000.0,136334000.0,1928.858633,2.652600e+11
2025-11-29 09:00:00,136334000.0,136770000.0,135300000.0,136073000.0,769.167574,1.045862e+11
2025-11-30 09:00:00,136000000.0,137631000.0,135600000.0,135744000.0,776.744970,1.060895e+11

In [21]:
df['close_shift1'] = df['close'].shift(1)

In [22]:
df.head()

,open,high,low,close,volume,value,close_shift1
2025-11-26 09:00:00,130779000.0,135485000.0,129600000.0,135366000.0,2216.723860,2.929944e+11,NaN
2025-11-27 09:00:00,135366000.0,138400000.0,134608000.0,136941000.0,2460.708463,3.364135e+11,135366000.0
2025-11-28 09:00:00,136989000.0,139868000.0,135691000.0,136334000.0,1928.858633,2.652600e+11,136941000.0
2025-11-29 09:00:00,136334000.0,136770000.0,135300000.0,136073000.0,769.167574,1.045862e+11,136334000.0
2025-11-30 09:00:00,136000000.0,137631000.0,135600000.0,135744000.0,776.744970,1.060895e+11,136073000.0

In [23]:
df['result'] = df['close'] - df['close_shift1'] #종가변화

In [24]:
df.head()

,open,high,low,close,volume,value,close_shift1,result
2025-11-26 09:00:00,130779000.0,135485000.0,129600000.0,135366000.0,2216.723860,2.929944e+11,NaN,NaN
2025-11-27 09:00:00,135366000.0,138400000.0,134608000.0,136941000.0,2460.708463,3.364135e+11,135366000.0,1575000.0
2025-11-28 09:00:00,136989000.0,139868000.0,135691000.0,136334000.0,1928.858633,2.652600e+11,136941000.0,-607000.0
2025-11-29 09:00:00,136334000.0,136770000.0,135300000.0,136073000.0,769.167574,1.045862e+11,136334000.0,-261000.0
2025-11-30 09:00:00,136000000.0,137631000.0,135600000.0,135744000.0,776.744970,1.060895e+11,136073000.0,-329000.0

나머지 판다스에 관한 공부할려면 아래 링크 참고하기 <br>
https://wikidocs.net/book/3488