In [1]:
import pandas as pd

data = [
    [157000, 39.88, 4.38],
    [51300, 8.52, 1.45],
    [68800, 10.03, 0.87],
    [140000, 228.38, 2.16]
]

index = ['NAVER', '삼성전자', 'LG전자', '카카오']
columns = ['종가', 'PER', 'PBR']
df = pd.DataFrame(data=data, index=index, columns=columns)
print(df)

           종가     PER   PBR
NAVER  157000   39.88  4.38
삼성전자    51300    8.52  1.45
LG전자    68800   10.03  0.87
카카오    140000  228.38  2.16

### 컬럼 선택
대괄호['컬럼명'] 을 통해서 단일 컬럼 선택 가능
- `df['종가']`
- 컬럼을 표현하는 시리즈 타입의 객체로 return 
    - index는 회사 이름
    - value는 종가

In [3]:
df['종가'] #series 객체

NAVER    157000
삼성전자      51300
LG전자      68800
카카오      140000
Name: 종가, dtype: int64

In [4]:
print(type(df['종가']))

<class 'pandas.core.series.Series'>

### 멀티 컬럼 선택
컬럼을 리스트로 구성한 후 인덱싱 기호에 리스트를 전달
- `df[['컬럼명1', '컬럼명2']]`
- (참고) 리스트로 구성해야 함 튜플로 구성하면 다른 의미가 됨.
- 리턴값은 또 다른 dataframe 객체가 됨.

In [5]:
df[['PER', 'PBR']]

          PER   PBR
NAVER   39.88  4.38
삼성전자     8.52  1.45
LG전자    10.03  0.87
카카오    228.38  2.16

In [7]:
print(type(df[['PER', 'PBR']]))

<class 'pandas.core.frame.DataFrame'>

### 로우 선택 
데이터 프레임에서 로우(row)를 선택할 때는 `iloc`나 `loc` 속성을 사용해야 한다.
| 속성 | 기능 | 사용 | 
| --- | --- | --- | 
| `loc` | **인덱스**를 사용해서 로우를 선택 | `df.loc['인덱스']` |
| `iloc` | **행번호를** 사용해서 로우를 선택 | `df.iloc[행번호]` |

In [9]:
df

           종가     PER   PBR
NAVER  157000   39.88  4.38
삼성전자    51300    8.52  1.45
LG전자    68800   10.03  0.87
카카오    140000  228.38  2.16

In [10]:
df.iloc[1]

종가     51300.00
PER        8.52
PBR        1.45
Name: 삼성전자, dtype: float64

In [11]:
df.loc['삼성전자']

종가     51300.00
PER        8.52
PBR        1.45
Name: 삼성전자, dtype: float64

### 멀티 로우 선택
리스트로 행 번호 또는 인덱스를 표현하고 이를 iloc나 loc 속성에 사용
- `df.iloc[[0,1]]`
- `df.loc[['인덱스1', '인덱스2']]`

In [12]:
df

           종가     PER   PBR
NAVER  157000   39.88  4.38
삼성전자    51300    8.52  1.45
LG전자    68800   10.03  0.87
카카오    140000  228.38  2.16

In [13]:
df.iloc[[0,1]]

           종가    PER   PBR
NAVER  157000  39.88  4.38
삼성전자    51300   8.52  1.45

In [22]:
df.loc[['NAVER', '삼성전자']]

           종가    PER   PBR
NAVER  157000  39.88  4.38
삼성전자    51300   8.52  1.45

### 로우 슬라이싱
`iloc`, `loc` 속성을 사용하여 슬라이싱

In [23]:
df.iloc[0:2]

           종가    PER   PBR
NAVER  157000  39.88  4.38
삼성전자    51300   8.52  1.45

In [24]:
df.loc["NAVER":"삼성전자"]

           종가    PER   PBR
NAVER  157000  39.88  4.38
삼성전자    51300   8.52  1.45