In [1]:
import pandas as pd

data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]

index = ['037730', '036360', '005760']
columns = ['종목명', '현재가', '등락률']

df = pd.DataFrame(data, index, columns)
print(df)

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  1.65
005760   ACTS  1185  1.28

### 특정 값 가져오기
위의 dataframe 에서 '036360'종목의 현재가를 출력하기
- `df.iloc['행번호', '열번호']`
- `df.loc['인덱스', '컬럼명']`

In [3]:
df.iloc[1, 1]

np.int64(1790)

In [4]:
df.loc['036360', '현재가']

np.int64(1790)

### 영역 가져오기
데이터 프레임에서 특정 영역 접근
- `df.iloc[행번호 리스트, 열번호 리스트]`
- `df.loc[인덱스 리스트, 컬럼명 리스트]`

In [7]:
df.iloc[0:2, [0,1]]

          종목명   현재가
037730     3R  1510
036360  3SOFT  1790

In [8]:
df.loc[['037730', '036360'], '종목명':'현재가']

          종목명   현재가
037730     3R  1510
036360  3SOFT  1790

In [9]:
df.iloc[0:2, [0,2]]

          종목명   등락률
037730     3R  7.36
036360  3SOFT  1.65