### 컬럼 추가
- `df['컬럼명'] = 시리즈 객체`
- 비트코인 일봉 데이터를 얻어온 후 각 거래일의 변동(range) 컬럼 추가하기
    - range = high - low

In [ ]:
pip install pyupbit

In [8]:
import pyupbit

df = pyupbit.get_ohlcv("KRW-BTC")

In [9]:
df.head()

,open,high,low,close,volume,value
2025-11-26 09:00:00,130779000.0,135485000.0,129600000.0,135366000.0,2216.723860,2.929944e+11
2025-11-27 09:00:00,135366000.0,138400000.0,134608000.0,136941000.0,2460.708463,3.364135e+11
2025-11-28 09:00:00,136989000.0,139868000.0,135691000.0,136334000.0,1928.858633,2.652600e+11
2025-11-29 09:00:00,136334000.0,136770000.0,135300000.0,136073000.0,769.167574,1.045862e+11
2025-11-30 09:00:00,136000000.0,137631000.0,135600000.0,135744000.0,776.744970,1.060895e+11

In [10]:
df['range'] = df['high'] - df['low']

In [11]:
df.head()

,open,high,low,close,volume,value,range
2025-11-26 09:00:00,130779000.0,135485000.0,129600000.0,135366000.0,2216.723860,2.929944e+11,5885000.0
2025-11-27 09:00:00,135366000.0,138400000.0,134608000.0,136941000.0,2460.708463,3.364135e+11,3792000.0
2025-11-28 09:00:00,136989000.0,139868000.0,135691000.0,136334000.0,1928.858633,2.652600e+11,4177000.0
2025-11-29 09:00:00,136334000.0,136770000.0,135300000.0,136073000.0,769.167574,1.045862e+11,1470000.0
2025-11-30 09:00:00,136000000.0,137631000.0,135600000.0,135744000.0,776.744970,1.060895e+11,2031000.0

### 컬럼 삭제
- `df.drop('컬럼명', axis=1)` 
- (참고) 로우를 지우고 싶으면 axis=0
- 원본은 그대로 유지되고 컬럼이 삭제된 새로운 데이터프레임 객체가 리턴됨.

<br>

> **⚠️ 참고 <br>**
> 
> 데이터 원본에서 삭제하고 싶을 때: `inplace=True` <br>
> inplace의 의미는 '제자리에', '본래 있던 곳에' 라는 의미로, <br>
> 제자리에 있던 곳에 해당 명령어를 수행하라~ 라는 의미

In [12]:
df = pyupbit.get_ohlcv("KRW-BTC")
df2 = df.drop('volume', axis=1)

In [14]:
df2.head()

,open,high,low,close,value
2025-11-26 09:00:00,130779000.0,135485000.0,129600000.0,135366000.0,2.929944e+11
2025-11-27 09:00:00,135366000.0,138400000.0,134608000.0,136941000.0,3.364135e+11
2025-11-28 09:00:00,136989000.0,139868000.0,135691000.0,136334000.0,2.652600e+11
2025-11-29 09:00:00,136334000.0,136770000.0,135300000.0,136073000.0,1.045862e+11
2025-11-30 09:00:00,136000000.0,137631000.0,135600000.0,135744000.0,1.060895e+11

In [15]:
# 원본에서 삭제하고 싶을 때
df.drop('value', axis=1, inplace=True)

In [17]:
df.head()

,open,high,low,close,volume
2025-11-26 09:00:00,130779000.0,135485000.0,129600000.0,135366000.0,2216.723860
2025-11-27 09:00:00,135366000.0,138400000.0,134608000.0,136941000.0,2460.708463
2025-11-28 09:00:00,136989000.0,139868000.0,135691000.0,136334000.0,1928.858633
2025-11-29 09:00:00,136334000.0,136770000.0,135300000.0,136073000.0,769.167574
2025-11-30 09:00:00,136000000.0,137631000.0,135600000.0,135744000.0,776.744970

### 시계열 데이터와 인덱스
시계열 데이터는 인덱스가 날짜와 시간으로 구성됨.
- 문자열로 표현된 날짜와 시간을 DatetimeIndex 타입으로 변환해서 사용해야 함.

In [21]:
# 판다스의 to_datetime으로 문자열을 datetimeindex 타입으로 변환하기
import pandas as pd

date = ["2021-04-09"] # 날짜가 여러개일 때
index = pd.to_datetime(date)

print(type(date))
print(index)
print(type(index))

<class 'list'>
DatetimeIndex(['2021-04-09'], dtype='datetime64[ns]', freq=None)
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [22]:
date = "2021-04-09" # 날짜가 한 개 일 때
index = pd.to_datetime(date)

print(type(date))
print(index)
print(type(index))

<class 'str'>
2021-04-09 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

### 로우 추가
loc 속성 사용
- `df.loc[인덱스] = 데이터`

In [24]:
df.head()

,open,high,low,close,volume
2025-11-26 09:00:00,130779000.0,135485000.0,129600000.0,135366000.0,2216.723860
2025-11-27 09:00:00,135366000.0,138400000.0,134608000.0,136941000.0,2460.708463
2025-11-28 09:00:00,136989000.0,139868000.0,135691000.0,136334000.0,1928.858633
2025-11-29 09:00:00,136334000.0,136770000.0,135300000.0,136073000.0,769.167574
2025-11-30 09:00:00,136000000.0,137631000.0,135600000.0,135744000.0,776.744970

In [25]:
print(df.index)

DatetimeIndex(['2025-11-26 09:00:00', '2025-11-27 09:00:00',
               '2025-11-28 09:00:00', '2025-11-29 09:00:00',
               '2025-11-30 09:00:00', '2025-12-01 09:00:00',
               '2025-12-02 09:00:00', '2025-12-03 09:00:00',
               '2025-12-04 09:00:00', '2025-12-05 09:00:00',
               ...
               '2026-06-04 09:00:00', '2026-06-05 09:00:00',
               '2026-06-06 09:00:00', '2026-06-07 09:00:00',
               '2026-06-08 09:00:00', '2026-06-09 09:00:00',
               '2026-06-10 09:00:00', '2026-06-11 09:00:00',
               '2026-06-12 09:00:00', '2026-06-13 09:00:00'],
              dtype='datetime64[ns]', length=200, freq=None)

In [26]:
date = "2022-01-01"
index = pd.to_datetime(date)

df.loc[index] = [100, 100, 100, 100, 100]

In [28]:
df.tail()

,open,high,low,close,volume
2026-06-10 09:00:00,92555000.0,94470000.0,91500000.0,92601000.0,1257.280333
2026-06-11 09:00:00,92560000.0,95800000.0,92558000.0,95623000.0,1035.236579
2026-06-12 09:00:00,95623000.0,96947000.0,94598000.0,96029000.0,933.995494
2026-06-13 09:00:00,96029000.0,96436000.0,95801000.0,96216000.0,259.966586
2022-01-01 00:00:00,100.0,100.0,100.0,100.0,100.000000

### 로우 삭제
- `df.drop(로우 인덱스, axis = 0)`
    - 원본은 그대로 유지되고 row가 삭제된 데이터프레임 객체가 리턴됨

In [42]:
df = pyupbit.get_ohlcv("KRW-BTC")

In [33]:
df.tail()

,open,high,low,close,volume,value
2026-06-09 09:00:00,94735000.0,94980000.0,91700000.0,92555000.0,1333.844960,1.244853e+11
2026-06-10 09:00:00,92555000.0,94470000.0,91500000.0,92601000.0,1257.280333,1.163889e+11
2026-06-11 09:00:00,92560000.0,95800000.0,92558000.0,95623000.0,1035.236579,9.792810e+10
2026-06-12 09:00:00,95623000.0,96947000.0,94598000.0,96029000.0,933.995494,8.944748e+10
2026-06-13 09:00:00,96029000.0,96436000.0,95801000.0,96360000.0,264.628534,2.543884e+10

In [31]:
index = df.index[-1]

In [32]:
index

Timestamp('2026-06-13 09:00:00')

In [43]:
df.drop(index, axis=0, inplace=True)

In [44]:
df.tail()

,open,high,low,close,volume,value
2026-06-08 09:00:00,95502000.0,96400000.0,94000000.0,94730000.0,1362.867831,1.297121e+11
2026-06-09 09:00:00,94735000.0,94980000.0,91700000.0,92555000.0,1333.844960,1.244853e+11
2026-06-10 09:00:00,92555000.0,94470000.0,91500000.0,92601000.0,1257.280333,1.163889e+11
2026-06-11 09:00:00,92560000.0,95800000.0,92558000.0,95623000.0,1035.236579,9.792810e+10
2026-06-12 09:00:00,95623000.0,96947000.0,94598000.0,96029000.0,933.995494,8.944748e+10