# 1. 실전 예상문제
제공된 학습용 데이터(phone_price_train.csv)는 휴대폰의 다양한 속성을 포함하고 있다. 이를 바탕으로 휴대폰의 등급 가격을 예측하는 다중 분류 모델을 개발하고, 가장 우수한 모델을 평가 데이터(phone_price_test.csv)에 적용하여 가격 등급 예측 결과를 도출하시오. 예측 결과는 아래의 [제출 형식]을 준수하여, CSV 파일로 생성하는 코드를 제출하시오.
* 예측결과는 F1 Score (macro) 평가지표에 따라 평가함

[제공 데이터]
1. car_price_train.csv : 학습용 데이터 (2,000건)
2. car_price_test.csv : 평가용 데이터 (1,000건, price_grade 컬럼 미제공)

[데이터 컬럼]
1. Blue : 블루투스 지원 여부 (0: 미지원, 1: 지원)
2. clock_speed : 프로세서 속도 (GHz)
3. fc : 전면 카메라 화소 (MP)
4. int_memory : 내장 메모리 (GB)
5. m_dep : 휴대폰 두께 (cm)
6. talk_time : 연속 통화 가능 시간 (시간)
7. touch_screen : 터치 스크린 여부
8. ... 기타 여러가지 특성
9. price_range : 가격 범주 (0: 저가, 1: 중저가, 2: 중고가, 3: 고가)

[제출 형식]
1. 제출 파일명 : result.csv
2. 제출 컬럼명 : pred (0~3)
3. 예측 결과 개수 : 1,000

In [48]:
# 출력을 원하실 경우 print() 함수 활용
# 예시) print(df.head())

# getcmd(), chdir() 등 작업 폴더 설정 불필요
# 파일 경로 상 내부 드라이버 경로(C: 등) 접근 불가

import pandas as pd

train = pd.read_csv('../../sample_data/part2/다중분류/휴대폰가격/phone_price_train.csv')
test = pd.read_csv('../../sample_data/part2/다중분류/휴대폰가격/phone_price_test.csv')

# 답안 제출 참고
# 아래 코드는 예시이며 변수명 등 개인별로 변경하여 활용
# pd.DataFrame변수.to_csv('result.csv', index=False)

# 여기에 코드를 작성하시오.
# 독립변수, 종속 변수 나누기
X_train = train.drop('price_range', axis=1)
y = train['price_range']

# 테스트 데이터 나누기
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X_train, y, test_size=0.2, stratify=y) 

# 학습하기
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

# 평가하기
from sklearn.metrics import roc_auc_score, f1_score
y_pred = model.predict(X_val)
y_proba = model.predict_proba(X_val) #다중분류일땐 지워주기

roc_auc = roc_auc_score(y_val, y_proba, average='macro', multi_class='ovr')
f1 = f1_score(y_val, y_pred, average='macro')

# 결과 내기
test_pred = model.predict(test)
result = pd.DataFrame(test_pred, columns=['pred'])
result

     pred
0       3
1       3
2       2
3       3
4       1
..    ...
995     2
996     1
997     0
998     2
999     2

[1000 rows x 1 columns]

# 1.풀이

In [49]:
import pandas as pd


train = pd.read_csv('../../sample_data/part2/다중분류/휴대폰가격/phone_price_train.csv')
test = pd.read_csv('../../sample_data/part2/다중분류/휴대폰가격/phone_price_test.csv')

# 데이터 유형 파악
#print(train.info())
#print(test.info())

# 결측치 파악
#print(train.isnull().sum())
#print(test.isnull().sum())

# X, Y 데이터 셋 분리
X = train.drop(['price_range'], axis=1)
y = train['price_range']

X_full = pd.concat([X, test], axis=0)
#print(X_full.shape)

# 학습, 검증 데이터 셋 분할
X_train = X_full[:train.shape[0]]
X_test = X_full[train.shape[0]:]
#print(X_train.shape, X_test.shape)

from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X_train, y, test_size=0.2, stratify=y)
#print(X_train.shape, X_val.shape, y_train.shape, y_val.shape)

# Randomforest 활용 모델 학습
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

# f1_score, Accuracy 활용 평가
from sklearn.metrics import f1_score, accuracy_score
y_pred = model.predict(X_val)
f1 = f1_score(y_val, y_pred, average='macro')
acc = accuracy_score(y_val, y_pred)
print(f1, acc)

# test 데이터 예측 및 결과 저장 (pred 1개 컬럼)
y_pred = model.predict(X_test)
result = pd.DataFrame(y_pred, columns=['pred'])
#result.to_csv('result.csv', index=False)

0.8628293754747172 0.8625

# 2. 실전 예상문제
제공된 학습용 데이터(drug_train.csv)는 환자의 나이, 성별, 혈압, 콜레스테롤 수치 등의 정보를 바탕으로 약물 종류(Drug)를 포함하고 있다. 이를 바탕으로 약물을 분류하는 모델을 개발하고, 가장 우수한 모델을 평가 데이터(drug_test.csv)에 적용하여 약물 종류 예측 결과를 도출하시오. 예측 결과는 아래의 [제출 형식]을 준수하여, CSV 파일로 생성하는 코드를 제출하시오.
* 예측결과는 F1 Score (macro) 평가지표에 따라 평가함

[제공 데이터]
1. drug_train.csv : 학습용 데이터 (150건)
2. drug_test.csv : 평가용 데이터 (50건, 약물 라벨 없음)

[데이터 컬럼]
1. Age : 나이
2. Sex : 성별 (F: 여성, M: 남성)
3. BP : 혈압 (HIGH, NORMAL, LOW)
4. Cholesterol : 콜레스테롤 (HIGH, NORMAL)
5. Na : 나트륨 비율
6. K : 칼륨 비율
7. Drug : 약물 종류 (drugA, drugB, drugC, drugX, drugY)

[제출 형식]
1. 제출 파일명 : result.csv
2. 제출 컬럼명 : pred (예: drugA)
3. 예측 결과 개수 : 50

In [89]:
# 출력을 원하실 경우 print() 함수 활용
# 예시) print(df.head())

# getcmd(), chdir() 등 작업 폴더 설정 불필요
# 파일 경로 상 내부 드라이버 경로(C: 등) 접근 불가

import pandas as pd

train = pd.read_csv('../../sample_data/part2/다중분류/약물/drug_train.csv')
test = pd.read_csv('../../sample_data/part2/다중분류/약물/drug_test.csv')

# 답안 제출 참고
# 아래 코드는 예시이며 변수명 등 개인별로 변경하여 활용
# pd.DataFrame변수.to_csv('result.csv', index=False)

# 여기에 코드를 작성하시오.
# 독립변수, 종속변수 나누기
X_train = train.drop('Drug', axis=1)
y = train['Drug']

# X_train + test = X_full
X_full = pd.concat([X_train, test], axis=0)

# 결측치 제거 -> 결측치 없음
# 범주형 데이터 One-Hot-Encoding
X_full = pd.get_dummies(X_full)

# X_full -> X_train, X_test
X_train = X_full[:train.shape[0]]
X_test = X_full[train.shape[0]:]

# 학습 데이터 나누기
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X_train, y, test_size=0.2, stratify=y)

# 학습
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

# 예측
from sklearn.metrics import f1_score, roc_auc_score
y_pred = model.predict(X_val)
y_proba = model.predict_proba(X_val) # 다중 회귀에서는 [:,1] X

f1 = f1_score(y_val, y_pred, average='macro')
roc_auc = roc_auc_score(y_val, y_proba, average='macro', multi_class='ovr')

# 결과
test_pred = model.predict(X_test)
result = pd.DataFrame(test_pred, columns=['pred'])
result

     pred
0   drugY
1   drugB
2   drugY
3   drugX
4   drugC
5   drugB
6   drugX
7   drugC
8   drugB
9   drugY
10  drugY
11  drugX
12  drugY
13  drugC
14  drugB
15  drugY
16  drugX
17  drugX
18  drugY
19  drugY
20  drugY
21  drugX
22  drugA
23  drugY
24  drugY
25  drugY
26  drugY
27  drugX
28  drugC
29  drugY
30  drugA
31  drugY
32  drugY
33  drugA
34  drugY
35  drugX
36  drugY
37  drugX
38  drugA
39  drugY
40  drugY
41  drugY
42  drugX
43  drugY
44  drugY
45  drugY
46  drugY
47  drugY
48  drugA
49  drugA

# 2.풀이(#1)

In [90]:
import pandas as pd

train = pd.read_csv('../../sample_data/part2/다중분류/약물/drug_train.csv')
test = pd.read_csv('../../sample_data/part2/다중분류/약물/drug_test.csv')

# 데이터 유형 파악
#print(train.info())
#print(test.info())

# 결측치 파악
#print(train.isnull().sum())
#print(test.isnull().sum())

# 범주형 변수 카테고리 파악
#print(train['Sex'].value_counts())
#print(test['BP'].value_counts())
#print(test['Cholesterol'].value_counts())

# X, Y 데이터 셋 분리
X = train.drop(['Drug'], axis=1)
y = train['Drug']

X_full = pd.concat([X, test], axis=0)
#print(X_full.shape)

# 범주형 변수 인코딩 - One-Hot Encoding
X_full = pd.get_dummies(X_full)
#print(X_full)

# 학습, 검증 데이터 셋 분할
X_train = X_full[:train.shape[0]]
X_test = X_full[train.shape[0]:]
#print(X_train.shape, X_test.shape)

from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X_train, y, test_size=0.2, stratify=y)
#print(X_train.shape, X_val.shape, y_train.shape, y_val.shape)

# Randomforest 활용 모델 학습
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

# f1_score, Accuracy 활용 평가
from sklearn.metrics import f1_score, accuracy_score
y_pred = model.predict(X_val)
f1 = f1_score(y_val, y_pred, average='macro')
acc = accuracy_score(y_val, y_pred)
print(f1, acc)

# test 데이터 예측 및 결과 저장 (pred 1개 컬럼)
y_pred = model.predict(X_test)
result = pd.DataFrame(y_pred, columns=['pred'])
result
#result.to_csv('result.csv', index=False)

0.8387114845938376 0.9

     pred
0   drugY
1   drugB
2   drugY
3   drugX
4   drugC
5   drugB
6   drugX
7   drugC
8   drugA
9   drugY
10  drugY
11  drugX
12  drugY
13  drugC
14  drugB
15  drugY
16  drugX
17  drugX
18  drugY
19  drugX
20  drugY
21  drugX
22  drugA
23  drugY
24  drugX
25  drugY
26  drugY
27  drugX
28  drugC
29  drugY
30  drugA
31  drugY
32  drugY
33  drugA
34  drugY
35  drugX
36  drugY
37  drugX
38  drugA
39  drugY
40  drugY
41  drugY
42  drugX
43  drugY
44  drugY
45  drugY
46  drugY
47  drugY
48  drugA
49  drugA

# 2.풀이(#2)

In [ ]:
import pandas as pd

train = pd.read_csv('../../sample_data/part2/다중분류/약물/drug_train.csv')
test = pd.read_csv('../../sample_data/part2/다중분류/약물/drug_test.csv')

# 데이터 유형 파악
#print(train.info())
#print(test.info())

# 결측치 파악
#print(train.isnull().sum())
#print(test.isnull().sum())

# 범주형 변수 카테고리 파악
#print(train['Sex'].value_counts())
#print(test['BP'].value_counts())
#print(test['Cholesterol'].value_counts())

# X, Y 데이터 셋 분리
X = train.drop(['Drug'], axis=1)
y = train['Drug']

X_full = pd.concat([X, test], axis=0)
#print(X_full.shape)

# 범주형 변수 인코딩 - One-Hot Encoding
X_full = pd.get_dummies(X_full)
#print(X_full)

# y를 라벨인코딩 수행
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
#print(y)

# 학습, 검증 데이터 셋 분할
X_train = X_full[:train.shape[0]]
X_test = X_full[train.shape[0]:]
#print(X_train.shape, X_test.shape)

from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X_train, y, test_size=0.2, stratify=y)
#print(X_train.shape, X_val.shape, y_train.shape, y_val.shape)

# XGBoost 활용 모델 학습
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train, y_train)

# f1_score, Accuracy 활용 평가
from sklearn.metrics import f1_score, accuracy_score
y_pred = model.predict(X_val)
f1 = f1_score(y_val, y_pred, average='macro')
acc = accuracy_score(y_val, y_pred)
print(f1, acc)

# test 데이터 예측 및 결과 저장 (pred 1개 컬럼)
y_pred = model.predict(X_test)
y_pred = encoder.inverse_transform(y_pred)
result = pd.DataFrame(y_pred, columns=['pred'])
result.to_csv('result.csv', index=False)

0.8877777777777777 0.9